* SQLi 1

** What you learn

An application should take all the necessary steps to sanitize user input and most importantly should not trust the user input.

** Writeup
:PROPERTIES:
:ATTACH_DIR: /home/arjen/Projects/cybersecurity-ctf/web-501-sqli-1/WRITEUP_att
:END:


When trying a SQL injection in the form by entering the username ~'~ and the password ~'~ nothing happens. Changing 1 of the 2 to something else however results in an error message being displayed.

#+BEGIN_SRC shell
Error description: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'test'' at line 1
#+END_SRC

When looking into [[https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection][SQL Injections]] you will learn about default strings such as ~value or 1=1~ or ~' or '1'='1~ to try and manipulate the search query. After some search of ~MariaDB~ and SQL Injections you will come across ~' or 1=1 #~ as an payload. This will not do anything yet.

The challenge boils down to a simple SQL Injection, however, instead of allowing all results the count of rows has to come back as 1. This can be achieved in several ways, the easiest is to use the ~admin~ username (see the hint in the login box title) and ~' #~.

~admin' #~
